---
title: 开发规范
copyright: true
typora-copy-images-to: 开发规范
date: 2019-05-10 14:02:43
tags: 规矩
categories: 开发
---



尝试过每个方法添加try

尝试过每个方法都返回flag

尝试过给每个方法添加装饰器

感觉是时候定一下规矩了...

<!--more-->

# 明确概念

错误，可能出现问题的地方出现了问题；

异常，不应该出现问题的地方出现了问题；

错误是业务过程的一部分，而异常则不是；

但是多数程序员习惯将一切非正常情况都看做错误，而不区分错误和异常，即使程序中可能有异常抛出，也将异常及时捕获并转换成错误。从表面上看，**一切皆错误**的思路更简单，而异常的引入仅仅增加了额外的复杂度。

因此明确一下，错误是业务逻辑里的**期望的**失败信息，异常是代码运行时被捕获到的**不期望的**异常信息；

# 历史

简单说一下之前做过的代码开发习惯尝试，看看是怎么对待异常和错误：

**其实就是个对待错误的历史。**

## 刚开始

就是每个函数/方法直接就返回结果，不怎么定义错误，在最后的主函数给来一个try-except，except到的异常就直接转换为错误返回了。

## 入门后

感觉之前的写法不太好，就把每个函数都添加个错误返回`{"result":"ok/fail","data":"xxxx"}`，结果就是下一步处理会好繁琐，好累。。。

## 成长期

写代码写的比较多，老感觉代码写的不漂亮，怎么都觉得不规范，就想找一个又省劲又简单的方式。于是就想到正常的返回值仍然通过return返回，把错误值当作异常来看待（哈哈，except到的是Exception），从大的方向上看就只需要处理两类值（所需值和非所需值）。然后就是把正常的错误定义为了一个所谓的安全异常（自定义安全异常），通过raise触发后，会被异常装饰器统一处理。这种方式最主要是定义了一个安全异常（错误）和能分类处理不同异常的装饰器。

```python
# 自定义错误（异常）
class SafeException(Exception):
    '''
    自定义正常业务触发，不需要追踪
    '''
    def __init__(self, errorvalue):
        self.value = errorvalue
    def __str__(self):
        return self.value


# 追踪非接口函数-方法装饰器
def deco_catch_func_exception(func_desc="内部方法"):
    def catch_exception(origin_func):
        def wrapper(*args, **kwargs):
            func_name = "未知函数"
            try:
                func_name = origin_func.__name__  #获取函数名
                u = origin_func(*args, **kwargs)  #执行装饰函数
                return u
            except SafeException as e:      # 自定义的错误（异常）
                logger.info(e)
                raise SafeException('{}'.format(e))  #继续往上抛异常（错误被转异常后被抓取后，继续往上抛）
            except Exception as e:          #默认异常
                traceback.print_exc()
                logger.error(e)
                raise Exception('{}-{} 方法异常：{}'.format(func_desc, func_name, e))
        return wrapper
    return catch_exception

# 追踪接口函数-视图装饰器
def deco_catch_view_exception(func_desc="外部接口"):
    def catch_exception(origin_func):
        def wrapper(*args, **kwargs):
            func_name = "未知函数"
            try:
                func_name = origin_func.__name__ #获取函数名
                u = origin_func(*args, **kwargs) #执行装饰函数
                return json.dumps(result_ok(u))
            except SafeException as e:
                logger.info(e)
                return json.dumps(result_fail('{}'.format(e)))    #异常转错误
            except Exception as e:
                traceback.print_exc()
                logger.error(e)
                return json.dumps(result_error('{}-{} 接口异常：{}'.format(func_desc, func_name, e)))
        return wrapper
    return catch_exception
    
# 方法示例1
# 对应接口的实际执行函数
@deco_catch_view_exception("用户注册接口")
def register_user(data):
    res = User.create_user(data)
    return res

# 方法示例2
# 对应内部运行函数
@deco_catch_func_exception("用户激活")
def active_user(cls, id, data):
    logger.info("接收到的参数：{}".format(data.get("is_active")))

    user = User.get_by_id(id)
    # todo 判断用户是否绑定工厂 和绑定工序
    if not user.role:
        raise SafeException("用户未绑定角色")   #错误转异常
    else：
        return "xxx"  #返回所需结果，字符串/列表/字典等


```

> 思想：先错误转异常（触发），再异常转错误（返回），异常信息被打印
>
> 理念：return正常信息，raise错误，打印exception



# 现在

最近看了GO的异常和错误处理方式方面的资料，有所触动，就想结合其中认同的方法，形成自己的开发规范。

---

1、接口函数（一个完整的业务逻辑）处加recover，执行异常转错误；

2、内部函数处，执行错误转异常；

-----

## 规范



- 没有失败的函数只返回有用值

- 失败原因只有一个的，返回值类型为Bool

-  需要返回错误的Error要放在返回值最后

- 错误值统一定义，而不是跟着感觉走

- 错误逐层传递时，层层都加日志



## 函数名命名规范

主要说一下分级的函数名

## GO注意事项

### 异常转Error

```go
defer func() {
        if p := recover(); p != nil {
            fmt.Println("panic recover! p:", p)
            str, ok := p.(string)  
            if ok {
                err = errors.New(str)   // 异常转错误
            } else {
                err = errors.New("panic")  //异常转错误
            }
            debug.PrintStack()
        }
    }()
```

### 错误转异常

```go
func openError(filename string) string {
    if filename=="test.txt"{
        return f.Name()
    }else{
        panic("打开的文件名")  //错误转异常
    }
}
```



> 思想：先错误转异常，后异常转错误，异常信息打印
>
> 理念：return正常信息，raise错误，打印exception